
public class ProjectEuler {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("Hallo.");
		
		
		String probDescr = "Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. \n" 
				+ "The first ten pentagonal numbers are: \n" 
				+ "1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... \n"
				+ "It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal. \n"
				+ "Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised;\n"
				+ "what is the value of D? ";
				
				
		Challenge challenge = new Challenge(44, probDescr);
		challenge.printProblem();

		challenge.printSolution();
		
		challenge.problemx();
	}
	
	
}
